plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.9'
    // id 'io.papermc.paperweight.userdev' version '1.7.2'
}

group = 'pl.dawcou'
version = '4.5.0-beta1'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    // Paper API
    compileOnly 'io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT'

    // Mapowania Papera
    // paperweight.paperDevBundle("1.20.4-R0.1-SNAPSHOT")

    // Biblioteka Mojang
    compileOnly 'com.mojang:authlib:6.0.54'

    // Pełny Netty z handlerami i pipelinem
    compileOnly 'io.netty:netty-all:4.2.18.Final'

    // Log4j
    compileOnly 'org.apache.logging.log4j:log4j-api:2.25.1'
    compileOnly 'org.apache.logging.log4j:log4j-core:2.25.1'

    // LOKALNE JAR-Y z folderu /libs
    // compileOnly fileTree(dir: 'libs', include: ['*.jar'])

    // Biblioteka ProtocolLib wymagana do skompilowania importów
    compileOnly 'net.dmulloy2:ProtocolLib:5.4.0'

    // Biblioteki do hashowania
    implementation 'org.mindrot:jbcrypt:0.4'
    implementation 'org.bouncycastle:bcprov-jdk18on:1.85.2'

    // Biblioteka bStats
    implementation 'org.bstats:bstats-bukkit:3.2.1'

    // Biblioteka 2FA
    implementation 'com.warrenstrange:googleauth:1.5.0'

    // Kyori Adventure API oraz Minidown/Legacy text (dla pełnego wsparcia komponentów)
    implementation 'net.kyori:adventure-platform-bukkit:4.4.1'
    implementation 'net.kyori:adventure-api:4.26.1'
    implementation 'net.kyori:adventure-text-minimessage:4.26.1'
    implementation 'net.kyori:adventure-text-serializer-legacy:4.26.1'
    implementation 'net.kyori:adventure-text-serializer-plain:4.26.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

processResources {
    filteringCharset = 'UTF-8'
    filesMatching('plugin.yml') {
        expand(version: project.version)
    }
}

shadowJar {
    archiveFileName = "${project.name}-${project.version}.jar"

    // Relokacje bibliotek
    relocate 'com.warrenstrange.googleauth', 'pl.dawcou.astralogin.libs.googleauth'
    relocate 'org.bstats', 'pl.dawcou.astralogin.libs.bstats'
    relocate 'org.json.simple', 'pl.dawcou.astralogin.libs.json'
    relocate 'net.kyori', 'pl.dawcou.astralogin.libs.kyori'
    relocate 'org.mindrot.jbcrypt', 'pl.dawcou.astralogin.libs.jbcrypt'
    relocate 'org.bouncycastle', 'pl.dawcou.astralogin.libs.bouncycastle'

    // Wyrzucenie zbędnego balastu
    exclude 'org/bouncycastle/math/**'
    exclude 'org/bouncycastle/internal/**'
    exclude 'org/bouncycastle/jcajce/**'
    exclude 'org/bouncycastle/jce/**'
    exclude 'org/bouncycastle/pqc/**'
    exclude 'org/bouncycastle/x509/**'
    exclude 'org/bouncycastle/i18n/**'
    exclude 'org/bouncycastle/iana/**'
}

tasks.build {
    dependsOn shadowJar
}

// Automatyczne usuwanie niepotrzebnego pliku -dev po zakończeniu budowania
// tasks.build.doLast {
    // fileTree("build/libs").matching {
        // include "*-dev.jar"
    // }.each { file ->
        // delete file
    // }
// }