# +-----------------------------------------------------------------------+
# |                     AstraLogin - Configuration file                   |
# +-----------------------------------------------------------------------+

# =========================================
#             General Settings
# =========================================
settings:
  # Wybierz język pluginu (Dostępne: pl, en)
  # Select the plugin language (Available: pl, en)
  language: en

  # Should the plugin check for newer versions of the plugin?
  check-updates: true

  # Should debug mode be enabled?
  debug-mode: false

  # Should the plugin save events (logins, registrations, etc.) to .log files?
  logs:
    # Should logging be enabled?
    enabled: true

    # What is the maximum number of logs? Older ones will be deleted.
    limit: 30

  backups:
    # Should automatic backups be enabled?
    enabled: true

    # How often should the backup be performed (e.g., "12 hours", "1 day", "48 hours")
    # NOTE: The minimum value is "12 hours", smaller values will be reset to 12 hours to protect the hard drive from overflowing
    interval: "24 hours"

    # What is the maximum number of automatic backups? Older ones will be deleted.
    limit: 10

# =====================================
#           Security Settings
# =====================================
security:
  ip-trust:
    # Should IP trust be enabled?
    enabled: true

    # Reputation Point Range
    score:
      min: -30
      max: 30

    # Reputation Level Thresholds
    levels:
      fatal: -20
      bad: -5
      neutral: 5
      good: 15

    # Points for events
    points:
      login:
        success: 1
        failed-password: -2

      twofa:
        success: 3
        failed-code: -2

      security:
        active-account-attempt: -1
        unknown-ip-login: -2
        ip-spam: -3
        multi-ip: -1

  ip-security:
    # IP-Lock: Prevents login if the player's IP address has changed.
    enabled: true

    # How many parts (octets) of the IPv4 address should the protection check when verifying the session/IP?
    # 4 = Full IP checking (strict, secure, but fails with dynamic IP)
    # 3 = Checks 3 parts (e.g., 46.205.197.X)
    # 2 = Checks 2 parts (e.g., 46.205.X.X - recommended for dynamic IPs in Poland)
    # 1 = Checks only 1 part (e.g., 46.X.X.X - very loose)
    ip-check-octets: 2

  # Protection against spam entering the server (e.g. bots/attacks)
  anti-spam:
    enabled: true        # Should this protection be enabled?
    max-attempts: 10      # Number of entries
    within-seconds: 60  # In what time (e.g. 120s = 2 minutes)
    tempban-time: "30 minutes" # How many minutes does it ban an IP for after exceeding the limit

  anti-multiaccount:
    enabled: true
    # How many accounts can be registered on ONE IP address?
    limit: 2

  logger:
    # Available options:
    # "mask" - masks the password with asterisks
    # "deny" - completely removes the line from the logs
    action: "mask"

  bcrypt:
    # The cost factor for the BCrypt algorithm.
    # Determines the number of iterations for password hashing.
    # Recommended range: 10-12 (Optimal balance between security and performance).
    # WARNING: Values above 14 may cause severe lag or server crashes on shared hosting.
    # Default value: 10
    cost: 12

# =================================
#          LOGIN FEATURES
# =================================
features:
  attempts:
    # Maximum number of login attempts before action is taken
    max: 3
    # 0 = Ban immediately after exceeding max attempts
    # 1 = One additional "margin" chance (kick) before the final ban
    margin: 2
    # Temporary ban duration (format: "number unit", e.g., "5 minutes", "1 hour")
    # This ban is stored in RAM and will reset after a server restart.
    tempban-time: "15 minutes"

  timer:
    # Enable or disable the login timer
    login-time-enabled: true

    # Set your login time
    login-time-limit: "2 minutes"

    # Should the login time be displayed on the boss bar?
    use-bossbar: true

    # Colors: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
    bossbar-color: "RED"

    # Styles: PROGRESS, NOTCHED_6, NOTCHED_10, NOTCHED_12, NOTCHED_20
    bossbar-style: "PROGRESS"

  session:
    # Should Sessions be enabled?
    enabled: true

    # Session duration. Examples: "5 minutes", "30 seconds", "1 hour"
    # Default is "5 minutes" if not specified correctly.
    session-time: "15 minutes"

  spawns:
    # After logging in, teleports the player to their last location, ignoring the spawn after logging in.
    teleport-to-last-location: true

  inventory:
    # Should player inventories be saved?
    enabled: true

    # Should the player's gamemode be saved?
    save-gamemode: true

  2fa:
    # Determine how much time a player has to configure 2FA
    setup-timeout: "2 minutes"

    session:
      # Should 2FA session be enabled?
      enabled: true
      # How long should a 2FA session last?
      session-time: "2 days"

  # Premium Login
  auto-login:
    # Should premium login be enabled?
    enabled: true

  password:
    # Minimum number of characters in a password
    min-password-length: 6

    # Maximum number of characters in a password
    max-password-length: 24

# =========================
#          VISUALS
# =========================
visuals:
  # Apply blindness effect to not logged in players.
  use-blindness: true

  # Hides players who are not logged in
  hide-unlogged-players: true