# +--------------------------------------------------------------------------------------------+
# |                     AstraLogin - Configuration file - Modern Auth System                   |
# +--------------------------------------------------------------------------------------------+

# ===============================
#          MAIN SETTINGS
# ===============================

# DO NOT change this value
config-version: 3.0.0

# Wybierz język pluginu (Dostępne: pl, en)
# Select the plugin language (Available: pl, en)
language: pl

# Should the plugin check for newer versions of the plugin?
check-updates: true

# ========================================
#          IP Protection & Security
# ========================================
security:
  ip-security:
    # IP-Lock: Prevents login if the player's IP address has changed.
    ip-lock-enabled: true

    # Protection against spam entering the server (e.g. bots/attacks)
    entry-protection:
      enabled: true        # Should this protection be enabled?
      max-attempts: 5      # Number of entries
      within-seconds: 120  # In what time (120s = 2 minutes)
      ban-time-minutes: 10 # How many minutes does it ban an IP for after exceeding the limit

  anti-multiaccount:
    enabled: true
    # How many accounts can be registered on ONE IP address?
    limit: 2

  logger:
    # Available options:
    # "mask" - masks the password with asterisks
    # "deny" - completely removes the line from the logs
    action: "deny"

# =================================
#          LOGIN FEATURES
# =================================
features:
  # Enable or disable the login countdown timer.
  login-time-enabled: true
  login-time-limit: 60 # Time in seconds

  # Enable or disable maximum login attempts.
  max-attempts-enabled: true
  max-login-attempts: 3

  # Session duration. Examples: "5 minutes", "30 seconds", "1 hour"
  # Default is "5 minutes" if not specified correctly.
  session-enabled: true
  session-time: "5 minutes"

  # After logging in, teleports the player to their last location, ignoring the spawn after logging in.
  teleport-to-last-location: true

# ========================================
#          Password Requirements
# ========================================
requirements:
  # Minimum number of characters in a password
  min-password-length: 6

  # Maximum number of characters in a password

  max-password-length: 16

# =========================
#          VISUALS
# =========================
visuals:
  # Apply blindness effect to unauthenticated players.
  use-blindness: true