name: AstraLogin
version: '${version}'
main: pl.dawcou.astralogin.AstraLogin
api-version: '1.18'
load: POSTWORLD

commands:
  astralogin:
    aliases: [al]
  zresetujhaslo:
    aliases: [resetpassword]
  zmienhaslo:
    aliases: [changepassword]
  zresetujip:
    aliases: [resetip]
  zaloguj:
    aliases: [login, l]
  zarejestruj:
    aliases: [register, reg]
  konto:
    aliases: [account]
  zresetujkonto:
    aliases: [resetaccount]
  listaip:
    aliases: [iplist]

permissions:
  astralogin.reload:
    default: op
  astralogin.update:
    default: op
  astralogin.spawn:
    default: op
  astralogin.resetpassword:
    default: op
  astralogin.resetip:
    default: op
  astralogin.resetaccount:
    default: op
  astralogin.account:
    default: op
  astralogin.iplist:
    default: op