name: AstraLogin
version: '${version}'
main: pl.dawcou.astralogin.auth.AstraLogin
api-version: '1.20'
load: POSTWORLD

commands:
  astralogin:
    aliases: [al]
  zresetujhaslo:
    aliases: [resetpassword]
  zmienhaslo:
    aliases: [changepassword]
  zresetujip:
    aliases: [resetip]
  zaufanieip:
    aliases: [iptrust]
  zaloguj:
    aliases: [login, l]
  zarejestruj:
    aliases: [register, reg]
  konto:
    aliases: [account]
  zresetujkonto:
    aliases: [resetaccount]
  zresetuj2fa:
    aliases: [reset2fa]
  listaip:
    aliases: [iplist]
  listakont:
    aliases: [accountslist]
  2fa:
    aliases: [tfa, auth]
  przenieskonto:
    aliases: [moveaccount]
  spawnlogowania:
    aliases: [loginspawn]
  wyloguj:
    aliases: [logout]

permissions:
  astralogin.reload:
    default: op
  astralogin.update:
    default: op
  astralogin.setspawn:
    default: op
  astralogin.delspawn:
    default: op
  astralogin.resetpassword:
    default: op
  astralogin.resetip:
    default: op
  astralogin.resetaccount:
    default: op
  astralogin.reset2fa:
    default: op
  astralogin.account:
    default: op
  astralogin.iplist:
    default: op
  astralogin.accountslist:
    default: op
  astralogin.moveaccount:
    default: op

  astralogin.iptrust.*:
    default: op
  astralogin.iptrust.info:
    default: op
  astralogin.iptrust.reset:
    default: op
  astralogin.iptrust.set:
    default: op

  astralogin.spawn.*:
    default: op
  astralogin.spawn.set:
    default: op
  astralogin.spawn.delete:
    default: op